[[data]]

name = "icon_refresh_red"
file = "glyphs.png"
src_x = 170
src_y = 0
src_w = 16
src_h = 26

[[data]]

name = "icon_refresh_yellow"
file = "glyphs.png"
src_x = 170
src_y = 26
src_w = 16
src_h = 26
